[package]
name = "Poker"
version = "1.0.0"
authors = []

[addresses]
contract_owner = "0xcafe"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
