[package]
name = "PokerGame"
version = "1.0.0"

[dependencies]
CryptoCore = { local = "../crypto-core" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }

[addresses]
crypto_core = "0x123"  # Will be filled with crypto-core's address
poker_game = "0x234"
